// This file is auto-generated by Netlify at build time.
// Never paste real credentials here — set them as Netlify environment variables.
window.__FIREBASE_CONFIG__ = {
  apiKey: "NETLIFY_VAR_FIREBASE_API_KEY",
  authDomain: "NETLIFY_VAR_FIREBASE_AUTH_DOMAIN",
  databaseURL: "NETLIFY_VAR_FIREBASE_DB_URL",
  projectId: "NETLIFY_VAR_FIREBASE_PROJECT_ID",
};

window.__APP_CREDENTIALS__ = {
  username: "NETLIFY_VAR_APP_USERNAME",
  password: "NETLIFY_VAR_APP_PASSWORD",
};
