// This file is auto-generated by Netlify at build time.
// Never paste real credentials here — set them as Netlify environment variables.
window.__FIREBASE_CONFIG__ = {
  apiKey: "{{FIREBASE_API_KEY}}",
  authDomain: "{{FIREBASE_AUTH_DOMAIN}}",
  databaseURL: "{{FIREBASE_DB_URL}}",
  projectId: "{{FIREBASE_PROJECT_ID}}",
};

window.__APP_CREDENTIALS__ = {
  username: "{{APP_USERNAME}}",
  password: "{{APP_PASSWORD}}",
};
