[build]
  publish = "/"

[[plugins]]
  package = "@helloample/netlify-plugin-replace"

  [plugins.inputs]
    fileTypes = ["js"]

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "config.js"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
